### PR TITLE
#1353 Fix for URLFrontier spout not taking into account the crawl ID

### LINKED ISSUE #1353: URLFrontier spout doesn't take into account crawl Id
The URLFrontier Spout
( https://github.com/apache/incubator-stormcrawler/blob/main/external/urlfrontier/src/main/java/org/apache/stormcrawler/urlfrontier/Spout.java ) doesn't take into account the crawl Id that can be specified in the configuration parameters (URLFRONTIER_CRAWL_ID_KEY = "urlfrontier.crawlid" defined in  org.apache.stormcrawler.urlfrontier.Constants)

This results in a mix of URLs coming from distinct frontiers in URLFrontier.

### PR DESCRIPTION
**Pull request by klockla**
Fixes #1353 

The URLFrontier spout will pass the crawl id to GetURLs according to the value of urlfrontier.crawlid

If not set, or equal to "ANYCRAWL"', the crawl ID will not be taken into account in the URLFrontier GetURLs request
(the request will be populated with an AnyCrawlID object which in turn results in a null crawl id on the URLFrontier side).

### For all changes:
- [X] Is there a issue associated with this PR? Is it referenced in the commit message?

- [X] Does your PR title start with `#XXXX` where `XXXX` is the issue number you are trying to resolve? 

- [X] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [X] Is your initial contribution a single, squashed commit?

- [X] Is the code properly formatted with `mvn git-code-format:format-code -Dgcf.globPattern="**/*" -Dskip.format.code=false`?

### For code changes:

- [ ] Have you ensured that the full suite of tests is executed via `mvn clean verify`?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file, including the main LICENSE file?
- [ ] If applicable, have you updated the NOTICE file, including the main NOTICE file?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

File: external/urlfrontier/src/main/java/org/apache/stormcrawler/urlfrontier/Spout.java [hunk 1]
```diff
@@ -131,12 +144,19 @@ protected void populateBuffer() {
...
+        GetParams.Builder builder =
                 GetParams.newBuilder()
                         .setMaxUrlsPerQueue(maxURLsPerBucket)
-                        .setMaxQueues(maxBucketNum)
                         .setDelayRequestable(delayRequestable)
-                        .build();
+                        .setMaxQueues(maxBucketNum);
+
+        if (URLFRONTIER_ANY_CRAWL_ID.equals(globalCrawlID)) {
+            builder.setAnyCrawlID(anyCrawlID);
```
Comment (jnioche) [inline external/urlfrontier/src/main/java/org/apache/stormcrawler/urlfrontier/Spout.java:154]: we can set it explicitly but given it is what it does by default we can probably get away with just adding a comment.
We could then remove the constant  `URLFRONTIER_ANY_CRAWL_ID` as well as `anyCrawlID` and simplify the logic?
Said differently, if a value is set use it, otherwise rely on the default behaviour?

Comment (klockla) [reply external/urlfrontier/src/main/java/org/apache/stormcrawler/urlfrontier/Spout.java]: Hi @jnioche , ok I removed references to anyCrawlId and populate the crawlId only if found in the configuration

**Review by jnioche — APPROVED** [review]

**Comment by jnioche** [comment]
thanks @klockla
